#---------------------------------#
#      general configuration      #
#---------------------------------#
version: 1.0.{build}

#---------------------------------#
#    environment configuration    #
#---------------------------------#
image: WMF 5

environment:
  cloudflare_api_key:
    secure: ydtOZVhhRRgu2IjG3r0vMtg+yizONRxwVwNYgrQ4T1t+RcZrO/7TxDQ7V95PxO7x
  github_access_token:
    secure: G0C3USmQ/x2d5wgpUOhYEe/leoYgdCDwW0yKJJuHBwjkNAlIelY7JgPJGJCCDZi/
  github_ssh_private_key:
    secure: PWRJDnOTJbu87GDzf0VluvyqA4WZHqQmP1zfCQ+5vdVkaKwHLzzhGb7DhnM1UnMv885G63OJJiuKDe92msQHgsC3AKfj7uEQwUPzc2G7by9/s5m5TPR6xi+HA2bepwbZvoyf2SFWqDbp63oD35CPHid2qizMXZsu9o96jF25Jg1FfFAK6+fg/RFnSGuPaRjNEaH+BAnwNLO2PUZ7+Ta6TkRLJaXIQihEk9mDDWBzUEOEb/3GtqDAWatWAQPgxORcIcfLBTYWZIXXdcezSw2YKopUH88QD5qeNyXnqPKDrJwloimSBI+An0eJIWiIuWm9KBXgSp1IGV3CFYEId75KtNJzwkzovFhsAVgAmPBVlnNf7bxcnfdS5aR08AgWrIOEJgnooMUsKbPLANNIWc4JO/idzcp7JL+UWPo3GIBQkdN2+ITgFd9HqjX1z92NbYfTkZqPryyopMXg8m47nLuFr8XvgfRgYMvMjIiywTsuPQ61xQVoflq1y1sqBPsgi+wO5ollLBTwqcWTMUMXD5ThAsxT3RJXVXCHmjWIhHKRiLg8EmHUNFNEMivSQVPPFiGHnCWDiG+26UaVlEt31kTGTjZdYWr5M+EkRz1B6cXyPo0AD+avmos5VH18Wl1zGI6qPZsC1E7d/taIBzIsGZOk3nFrvycRcjR5qHk9tULpSpUN44CzyyYLSSJWYOvQqbxs/m1j7u/2xEEfhQMI9AWRv1rwhxB3K9PuC8a5c4CVNpOnSc9KfdlXQpwGd5ax+NbES1KBxUWg+kjNYr14/w5YU3I/OxP2L5BJsuGfq8E2Z+oEae/3TBYDKBGtbNet05Kq+gltbBusIAk3Mdb5vybJp4iCQoQgFpXulTVlk9RcM/RQwsuqkugHC9Qo610u5jqcj6yA6LanvYg7FlNyDQAMXy5XKHldrnDCcUSQSUYWMI/dbXlqhfWiwBWF0uKDby8Z6y3kg2rQCYQ/W8a3zaUt4Z+KRdLT8kVc0DmqtYfJFrcq2owFACKC4K3esxzLDTEl1EFniWvUn0+IKuTPbFemv8ydSHmc3L9OIDeCl/CqlcK6AK/wnoeNHiyV6QTOfGOxaKD4DzwOMh0vKSt0dWueodTA54bY6FZh9MBRQCpVKqA6KmdBuu/pUrlvLdDLXmbClFqoyGKe3r/kb13VxpXZHf4U1eRli65aqwSsg+hjHBS5R9Z4VyU0/Avw4pKAkfV5HhSJbXZa8jfUFp8ufucAq2SLZWtlmYWEQb7xr97AhrVg9HNfaG5k8ZNUvOZN7gg7iFYPXUPB67RmZ6VP3qX9UHX+CP6zmX3u6DCakiWXzr+pIiTTWtVNtEG7ifq436Lq921AWpjX1E+BMEoTGb6ks26dApPZ4eLxRyyvo3RcWhZGdPxOjShhZYtIfmZEhchSlmg1pLasQx5rXy++1PBG+7ktJkUoC9WiZJNc6QWlbrhGwfilKVyoedCoXpAZEL6Wr2tn4cj2XbY2Cp0GuqscAcAfnnM1IHZHUje63aw3/Z2G5eYoHNCOZZ3rHC2DKwjr5kthw3/wrTE85HIvzN+W3c47EsqdMtpxyR3iOf7IlZAzc2p0vTwRG5vMiLVMSxJDSTTWerSYrALpZdjiJlzxfzXFdJO9SmJjB02mh9eP/oU+b0ykQxP3VdUJNLx9PYU70cHPmfJekD8wrdvs6+PYFbFLEApk5+YDqtRp+/tPobEianEl5Om+9+F+RUCX8YbqvCUtv29x4vJ1yJjFgQJ9AbTioT1M97f9AS2EwXylUJ4THyZZ0JhMHuVGxpk1GozaVk+ZXAzEYi1jeFBnWeIPLGgJAdooqyWElLhOTaOLxnRvYGbwbOoZG1GZbOLm5Ddq2k+1k/UStsWjuGuuyUVGy036vRxnRzCSsEhNXqNOyBGmsuc7yGDyFqvDpCefN3jSNq7mUNdg6IHe30Pm2ts1YSiSo3bgUXDuhFqcuSwLM1pNB9MjKWAOMcOVZdvbov70W+aL6Io5E92xarvcgU8Kv1DjxPfKaIWfhD3ivRnHXU/1hG9L8AP/c5LO44z2WlFgMg6XRTpqJCVlqy5EDPJWE/I96t0/YsBoqhKdu8N+bdh1BulTqI60HIjjY7z5U4PO93PItJfsDt2gFa3GjKc+skzHTLL6vx6DJDTMsizCYhP5o0+D6Fbh6igrC9Pw7cY+JzWHa/qa37zcGYIfA6mZkDudMW2kTWPOmdzizKC9uHAveo5IEvTcP/RejTyU+1gBs/ELP1lj2TDh+ea5pi8FCz0BawVS1JDq7tIARrnPhF563/oNansHezgragPY7UReKNHWO14Aedlw6PJF+2BCNHKbW6V5Osi2Ls60kgBZVpUl+8dSg1AOSpt32wLP7oy2Hz4sEP9wDpnmghpixC2WlM0+Bv2JP8a7fw1BqOrIQFWZJnhOwCOB4n7okIM6XJCZy4emrXG2Q3h0bTSV9rYbiMIKJ5wM5qxQSWDz9DGybWlHcwlQzfALNMoTr5MrRsNWZrKZSFlTaUoeQpK6TsfsRkcm0qoTjv+HjrLzXj1gzZJ4njrtOfD7Vpi3DsdLaclF6IZt663pswz5YvNx/X38W+jMje4L7stvD7csIrBJxBy1q4lHLwNH6StqJCFyp+ut9TXiBd9DkNpSNw6zbEssLAUqk0PN/JKYfqPwJO/2NHqS14MtJxl33RIMEJpUTaaDG4Lt95GqVqjupfRU7daoegGC8G3qeY2LV49EFgAnyM/ELfcitOojyIlE7NqCb0EYSkiCsVAygJKjVaK1C9jdsj1aYlwJL9aJTBgnk4FKLKIh7P//dQy/IW00PLDgov2XbdIOV5xIoKdF88Lrb1HrSOEjlaKtb88CDaW/8tZoLaW7RVScEO28wANyHCccKLafSPDM88rNijsvj04cNx2VxvT5AW7CpnEGqpMaCiWeMej9I2t9D4MwUKRM6nZptFtTwRcQ7svSt5WRTuxWlCcxQnhBps5C6EwXR5IwKvpSlG1LBxqmLfoUmyAkAwL1LbhzHNEKJNadmp6VuLldvU7n7V2a4h0QgSYcpQCTCLRacmyJp2TEBQdfdgXwffvSsM+Wuua1PyaszO9b9DIPd37LPzJezS4ilyeTJyqTSZaiX04+xDBzCes9GWBzriqpPB3WwCQ2nRrvHd9Sf76Xr/zezrip+MV06CJ3SFAv8ABeGX3WJLyJZtdOc1VY7c2IxRhF9TcYo5IoE1twhe4Be6jvOyQOH8rgJ2jwp4pwwkMZBSAfu1qjoe/En9RlwF0HXud83UmAzmzfhfNbNrubPbj2jj+yUSrCP3hnLjQHwtld5DWHlTyGHW8+TygCzeOELtEfK7ZxuBb+lEPb1A4+leGRN2J6MqBvExR2vmMXc0x5jnurc+xZFum+VpqkovCzmV5W+66pObCBgXiNeqHvPE74jAbtz5M92Jln2mjyAaH5w0o/CwKdrKVo47vlM2lkFQIlBQsB8i21KRv7fhfZS8awgr1//SeMzW3anEKFGakmRDE+VLXI90SnQEjbnTZSYiszCj/CZQSn4r/C2/Et2ayzsjFVpCV0+cYkisAVm1myx4h39sLHh3weH4si4Qj43Utm9WrA0razOy0XbibH0dRpjsunU060Q44w+jSHRkZsLvb7sKgaBSHl24rgTW8cTgJOYiY3Q45k0hGP7Zt5cYY5rhf3jsVntkTt1wZ/2D5Vd6Et95aOF0e6ZC1GkoSgTfS7ZgigkUkw87KrHfVy4aivfq8yDhL9ehQrpgPbLFrYxKQ0aqWfxVuEvHqSqDyqPz5Fk06ynGTKI68G777bffoTdcWwiTtnoaqVUktYKbt4nsu7/gveB779RBfELM/+bSzFGCXseO+aIkRLrg0+9XPXcFKffJiiKFX29HTVkQc0x2oSbxI4kJ9OkDE8qzvo9MFBi49c+u0EHyh0S13sZDjdXpC/wOrK8nozA4BDsH1PiJaitllrotRIzQ9UUB4E6XeTkjfOOjXRND4otPOnXc9DCcHqlPUiXo67JIf/QORiYn7K+0ZIhzXdbFHz4N8Y/RL/VP5D+HrbwAHJP1pzc21d26g7+PYcdpH9Cj4vZ35M/tg2BHjGLZLHzQwANTm5Twchw++GyLsFc8Lbi22M+TLudfb61bfeZy4XKNJZFz+E2chFEZ3SiP4hhyNzSuJ3dcO7dfdlv4YXE0zt09ku13h8rhtj73eJktFxi7Xj/YedqDjadrACuogyqRax2IjFXWusRTWh7aFwTWOcMOqFMprIKUvak29Mw5beihBDQQpsXchCGWzXldOIx/iDmCWM/0s5eR5r648HzCT3LxhjSPbxvkh3XsPV1v+ZmQP9WyKo7ppqp9WI4zEabXR83djVAzAyJsj4my1P8GIgZbYir9nk6N6NEl9WA+ZSvFoeTTGt4Aw3Bp12Sr2dXDvKr/jlgma02OSc5QBCvL/NXP27NELhfmeA520RFYTDhY3mvnkGld+rceewje09symyJra9SmCLL5Rl0fKqoNjMFxdVVwzMhQ==

install:
  - pwsh: |
      $ErrorActionPreference = 'Stop'

      $fileContent += $Env:github_ssh_private_key.Replace('_', "`n")
      Set-Content -Path "$Env:USERPROFILE\.ssh\id_rsa" -Value $fileContent

      # Force update any submodules. We need this so we can merge any changes to public.
      git submodule update --init --recursive

      # Checkout the public submodule master branch so it won't be deteached.
      Set-Location -Path .\public
      git checkout master

      # Return back to the project root which is where we will build the website from.
      Set-Location -Path ..\

      # Install hugo via Chocolatey.
      choco install hugo

      # Configure git so we can commit submodule changes back to GitHub.
      git config --global credential.helper store
      Set-Content -Path "$HOME\.git-credentials" -Value "https://$($Env:github_access_token):x-oauth-basic@github.com`n"
      git config --global user.email "paul@duskcs.com"
      git config --global user.name "Paul Shamus"

#---------------------------------#
#       build configuration       #
#---------------------------------#
build_script:
  - pwsh: |
      $ErrorActionPreference = 'Stop'

      hugo version

      # Store the current build version which will be displayed on the website footer.
      Set-Content -Path .\content\version -Value $Env:APPVEYOR_BUILD_VERSION

      # Generate updated website content.
      hugo -t beautifulhugo

#---------------------------------#
#     deployment configuration    #
#---------------------------------#
deploy_script:
  - pwsh: |
      $ErrorActionPreference = 'Stop'

      Write-Host "Staging updated website content"
      Set-Location -Path .\public
      git status
      git add .
      git status

      Write-Host "Committing website content"
      $commitMessage = "Rebuilding site $(Get-Date -Format R)"
      git commit -m "$commitMessage"
      git status
      git push origin master

      Write-Host "Committing parent repository submodule checksum changes"
      Set-Location -Path ..\
      git checkout master
      git add public
      git commit -m "$commitMessage - [skip ci]"
      git push origin master

after_deploy:
  - pwsh: |
      $ErrorActionPreference = 'Stop'

      Write-Host "Purging Cloudflare CDN cache"
      $headers = @{
          'X-Auth-Email' = 'paul@duskcs.com';
          'X-Auth-Key' = "$($Env:cloudflare_api_key)";
          'Content-Type' = 'application/json'
      }

      # Retrieve zone ID.
      $zoneId = (Invoke-RestMethod -Uri 'https://api.cloudflare.com/client/v4/zones?name=duskcs.com' -Headers $headers).result.id

      # Purge the Cloudflare CDN cache.
      Invoke-RestMethod -Uri "https://api.cloudflare.com/client/v4/zones/$zoneId/purge_cache" -Method Post -Headers $headers -Body '{"purge_everything":true}'
