version: 0.0.{build}

#---------------------------------#
#    environment configuration    #
#---------------------------------#
image: WMF 5

environment:
  access_token:
    secure: G0C3USmQ/x2d5wgpUOhYEe/leoYgdCDwW0yKJJuHBwjkNAlIelY7JgPJGJCCDZi/

install:
  - git submodule update --init --recursive
  - git submodule update --checkout public
  - ps: choco install hugo
  - git config --global credential.helper store
  - ps: Add-Content "$HOME\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
  - git config --global user.email "paul@duskcs.com"
  - git config --global user.name "Paul Shamus"

#---------------------------------#
#       build configuration       #
#---------------------------------#
build_script:
  - ps: hugo version
  - ps: hugo -t beautifulhugo
  - ps: Get-ChildItem -Path .\public

#---------------------------------#
#     deployment configuration    #
#---------------------------------#
deploy_script:
  - cd public
  - git add .
  - ps: $commitMessage = "Rebuilding site $(Get-Date -Format R)"
  - ps: git commit -m "$commitMessage"
  - git push origin master
